### ISSUE TITLE
Handle optimizing existing original image again

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#239]
- Do not re-optimize the original again if there is already an optimized version
- But what if the quality setting changed in the meantime, i.e. from 60 to 80? Generate _another_ optimized version or edit the existing one? How to keep track of the multiple versions?

**Comment by erikyo** [comment]
Yep you are right, it's generally advisable to avoid multiple rounds of compression, especially with different formats (e.g., compressing from highly compressed JPEG to WebP). In such cases, artifacts tend to accumulate and it didn't lead to a good result to change the initial format.

Take a look at this -> https://cloudinary.com/blog/why_jpeg_is_like_a_photocopier

imho, keeping the original file is a good practice (the original one and not the resizes). This allows for the possibility to revert decisions and provides a baseline for comparison. perhaps adding a field to the attachment meta such as "source_media" might be enough.

**Comment by swissspidy** [comment]
> Yep you are right, it's generally advisable to avoid multiple rounds of compression, especially with different formats (e.g., compressing from highly compressed JPEG to WebP)

Agreed. That's something I haven't fully implemented yet. Ideally before you first upload an image, we should check whether the image has a reasonable size and if not, force it to optimize.

> imho, keeping the original file is a good practice (the original one and not the resizes). This allows for the possibility to revert decisions and provides a baseline for comparison. perhaps adding a field to the attachment meta such as "source_media" might be enough.

Yep, that's already implemented.

In this issue here, which I opened after just having a discussion with @ntsekouras, I want to figure out how to address this case:

1. You insert an existing image A on page X and also on page Y.
2. You edit page X in the editor, you click to compress that image with quality 80, and a new compressed version (image B) is uploaded
3. You edit on page Y, you still see image A. Now you compress it with quality 60.
4. Is a new image C uploaded? What happens to image B? How can the user manage all these different versions of the image?

**Comment by ntsekouras** [comment]
Maybe an approach would be to keep just one compressed version and in the above scenario, we would delete the previous compressed one and keep the new one. In order to do that though it would probably require to update the core Image block to check if there is a compressed version and pick the proper image url(and maybe some additions in how the srcset is produced(🤔 ) ? 

If the above is viable, we would keep all the other attributes(caption, title, etc..) in sync too.

**Comment by swissspidy** [comment]
> In order to do that though it would probably require to update the core Image block to check if there is a compressed version and pick the proper image url

I would probably just replace the file on disk, but not actually upload a new attachment to the database. Then you don't have to worry about keeping things in sync etc.
It might warrant an "Are you sure?" dialog to let the user know that existing images on their site will be replaced with the new version. While in this case the previous version with quality 80 is replaced with the 60 one, it's not really data loss (you can always re-compress the original at 80 to get it back).

Caveat: what happens if you convert the image to another file format instead?

Some alternatives:

- Simply upload a new version, do not touch any other versions. User may end up with X different images in different quality settings. Not the end of the world, but clutters the media library and disk a little bit.
- ..?

**Comment by swissspidy** [comment]
That's a good point with different use cases 👍 

> Additionally, it would be helpful to keep attributes such as caption and title synchronized.

Do you mean true (unidirectional or bidirectional?) synchronization or just one-off copying these attributes upon compression?

**Comment by swissspidy** [comment]
Another use case I'd like to cover here:

1. Upload image A to a post
2. Compress image A with quality 80 -> results in image B
3. Now if you want to compress image B with quality 60 -> should it compress A with quality 60 or B with quality 60 (which would essentially be A with quality 48 (0.8 * 0.6))

**Comment by erikyo** [comment]
IMHO - should it compress A with quality 60 (to avoid photocopy effect)
