### ISSUE TITLE
Add more options to preferences modal

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#256]
* Generate thumbnails client-side? yes/no
* Override big image size threshold? 0 to disable
* Compress new images during upload? yes/no
* Whether to compress but keep the file type (i.e. jpeg -> jpeg, png -> png)
* Alternatively, preferred image format (e.g. convert everything to webp/avif)
	* If so, which library to use (browser, MozJPEG, vips, libavif 
	* Needed for poster images

Maybe a dropdown per file type to have a mapping?

```
[x] Compress new images during upload?
```

Preferred image format (used for things like poster images etc.):

<ul>
<li>JPEG (browser
<li>WebP (browser, if supported)
<li>JPEG (wasm-vips, uses MozJPEG)
<li>WebP (wasm-vips, uses libwebp)
<li>AVIF (wasm-vips, uses libavif)
</ul>

Choose preferred behavior:

<table>
<tr>
 <td><code>.jpeg</code>
 <td>
<ul>
<li>Do nothing
<li>Compress (browser)
<li>Compress (wasm-vips, uses MozJPEG)
<li>Convert to WebP (browser, if supported)
<li>Convert to WebP (wasm-vips, uses libwebp)
<li>Convert to AVIF (Wasm-vips, uses libavif)
</ul>
<tr>
 <td><code>.jpeg</code>
 <td>
<ul>
<li>Do nothing
<li>Compress (browser)
<li>Compress (wasm-vips, uses MozJPEG)
<li>Convert to WebP (browser, if supported)
<li>Convert to WebP (wasm-vips, uses libwebp)
<li>Convert to AVIF (wasm-vips, uses libavif)
</ul>
<tr>
 <td><code>.png</code>
 <td>
<ul>
<li>Do nothing
<li>Compress (browser)
<li>Compress (wasm-vips, uses libspng)
<li>Convert to WebP (browser)
<li>Convert to WebP (wasm-vips, uses libwebp)
<li>Convert to AVIF (wasm-vips, libavif)
</ul>
<tr>
 <td><code>.webp</code>
 <td>
<ul>
<li>Do nothing
<li>Compress (browser, if supported)
<li>Compress (wasm-vips, uses libwebp)
</ul>
<tr>
 <td><code>.avif</code>
 <td>
<ul>
<li>Do nothing
<li>Compress (wasm-vips, uses libavif)
</ul>
<tr>
 <td><code>.gif</code>
 <td>
<ul>
<li>Do nothing
<li>Convert to MP4 (ffmpeg)
</ul>
<tr>
 <td><code>.heic</code>
 <td>
<ul>
<li>Do nothing (essentially disallow upload)
<li>Convert to JPEG (libheif-js, then browser)
<li>Convert to JPEG (libheif-js, then wasm-vips, uses MozJPEG)
<li>Convert to WebP (libheif-js, then browser, if supported)
<li>Convert to WebP (libheif-js, then wasm-vips, uses libwebp)
<li>Convert to AVIF (libheif-js, then wasm-vips, uses libavif)
</ul>
</table>

Note: ffmpeg also has libwebp, but seems pointless as there is already wasm-vips. So maybe remove that again?

Note: both jsquash and wasm-vips use mozjpeg, so can remove the former

Note: vips also supports jpeg xl

**Comment by swissspidy** [comment]
Going with this for now:

<img width="806" alt="Media preferences modal in the block editor" src="https://github.com/swissspidy/media-experiments/assets/841956/a8a0fa8a-7e96-4f35-8e10-92b0b1221299">
<img width="794" alt="Media recording settings" src="https://github.com/swissspidy/media-experiments/assets/841956/7a967743-ba48-4d98-b7b0-e547e0339b4d">

**Comment by erikyo** [comment]
- For some formats family would be cool to have some some additional options (eg. to enable the progressive loading for jpegs)
- To set a different compression rate for the different codecs.

**Comment by swissspidy** [comment]
I thiught about that, but need to think more about how to not make that confusing.

**Comment by swissspidy** [comment]
I suppose we could start with a quality setting per format. Not sure if other stuff is even supported.

That would match existing behavior in core, where the default quality setting for jpeg and webp was different (82 vs 86)

**Comment by erikyo** [comment]
> I thought about that, but need to think more about how to not make that confusing.

Seems fair to me though maybe an advanced tab for this purpose of fine tuning might appeal cool

> I suppose we could start with a quality setting per format. Not sure if other stuff is even supported.

I remember correctly WordPress doesn't support progressive jpeg (even if I think it's a shame https://www.smashingmagazine.com/2018/02/progressive-image-loading-user-perceived-performance/). 

If you could make a table "format in" "format out" (select) and quality (range slider) would be more than excellent

| enabled | extension (in) | desidered out | quality     |
|---------|----------------|---------------|-------------|
| X       | jpeg/jpg       | mozjpeg       | -----*- 82% |
| x       | png            | webp          | -----*- 86% |
|         | webp           |               |             |
|         | avif           |               | ---*--- 50%|

(....)

**Comment by swissspidy** [comment]
> I remember correctly WordPress doesn't support progressive jpeg

vips / mozjpeg does, so that's nice :)

> If you could make a table "format in" "format out" (select) and quality (range slider) would be more than excellent

Yeah that's what I was getting at with the table in the issue the description, and it would definitely provide most flexibility, but also make things more complex. But as you say, maybe an advanced tab for this would be best.

**Comment by swissspidy** [comment]
Reopening for looking into advanced configuration
