### ISSUE TITLE
Add option for progressive (interlaced) image output

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#355]
https://core.trac.wordpress.org/changeset/57607

Vips supports it, but this needs to be carefully implemented as it throws an error if providing the progressive option for a format that doesn't support it.

Question: One general option in the modal or one for each format (like quality)?

**Comment by erikyo** [comment]
I would like to enable it only for jpgs for example, and I think doing like "one for each format" is preferable to give users more granularity in the choice of the preferred encoding method

**Comment by swissspidy** [comment]
There's gonna be so many options eventually 😄

**Comment by erikyo** [comment]
you are right but progressive jpg are preferable while a progressive png can size the 20% more than the "standard" one (and that's why I would avoid enabling it for pngs)

**Comment by swissspidy** [comment]
Implementation notes for myself:

Add a hardcoded map with available options per format with types and everything (schema?).
Then loop through them according to the chosen output format.

Setting key might be confusing, e.g. if jpeg_outputFormat is AVIF, then AVIF quality would be under jpeg_quality? Or better jpeg_avif_quality?
Do we delete stale preferences after changing formats?

**Comment by swissspidy** [comment]
From https://github.com/swissspidy/media-experiments/issues/347#issuecomment-2139645667:

> Aside: this is missing a "default image quality" checkbox

**Comment by swissspidy** [comment]
New layout:

<img width="797" alt="Screenshot 2024-06-22 at 14 43 29" src="https://github.com/swissspidy/media-experiments/assets/841956/8a987464-9de6-474a-a826-c3120ce5dbb5">

<img width="804" alt="Screenshot 2024-06-22 at 14 43 19" src="https://github.com/swissspidy/media-experiments/assets/841956/f15425d6-f5c8-4bbf-beb2-44fadb329702">

**Comment by swissspidy** [comment]
Useful testing tool: https://google.github.io/attention-center/
