### ISSUE TITLE
Keep date folder when optimizing existing media

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#465]

**Comment by swissspidy** [comment]
This was reported by @PatriciaBT, but I actually cannot reproduce the issue. The date folder is already kept.

What I did:

1. Deactivate Media Experiments
2. Upload an image to a blog post from January 2024
3. The image was stored in `wp-content/uploads/2024/01`
4. Activate Media Experiments
5. Edit the blog post, optimize the existing image
6. The optimized image is also stored in `wp-content/uploads/2024/01`

Proof:

<img width="539" alt="Screenshot 2024-05-10 at 15 11 58" src="https://github.com/swissspidy/media-experiments/assets/841956/c59d9750-f052-4921-928b-120074e16ea8">

Aside: the file names are incorrect, I'll fix that separately.

**Comment by patriciabt** [comment]
Thank you @swissspidy 
When I add a file to a post from another month, it goes anyway in the current month, so it is indeed probably unrelated to the plugin.
Also on your above image, it's month May (5) right?

**Comment by swissspidy** [comment]
Ah, you're right! My bad 🤦 

So I just looked into this more closely...

> When I add a file to a post from another month, it goes anyway in the current month, so it is indeed probably unrelated to the plugin.

**I think this is a bug in WordPress.**

If I insert an image block in an old post from January, click on "Media Library" and upload an image in the popup there, the file is going to the January folder.

<img width="749" alt="Screenshot 2024-05-10 at 16 39 51" src="https://github.com/swissspidy/media-experiments/assets/841956/cbb013ed-a078-4c86-89d9-aedf49198df0">

(This is handled by `media_handle_upload()` and only works for post types other than page.

However, if I drag & drop an image into the editor, the file actually goes to the current month (May).

So this is inconsistent. I'll see how/where we can fix that in WordPress.

----

There is also another use case:

1. Upload an image to a blog post from January, the image is stored in `2024/01`.
2. Create a new post in February and insert the existing January image
3. Optimize the image
4. Should it now be uploaded in `2024/01` (which is the date of the post) or in `2024/01` (the date of the original image)?
