### ISSUE TITLE
Saliency detection

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/media-experiments#5]
Detect the most relevant part of an image to improve thumbnail cropping. For example using [MediaPipe’s object detection solution](https://developers.google.com/mediapipe/solutions/vision/object_detector/).

**Comment by swissspidy** [comment]
VIPs supports smart cropping (`vips_smartcrop()`) with the `attention` strategy (`--smartcrop attention`), which is also the default. "This one searches the image for features which might catch a human eye"

**Comment by johnbillion** [comment]
[libvips is available in wasm](https://github.com/kleisauke/wasm-vips) which means we could use [Sharp](https://github.com/lovell/sharp) client-side and get some really powerful image processing capabilities without needing the PHP bindings.

[Looks like StackBlitz has done some work on this](https://blog.stackblitz.com/posts/bringing-sharp-to-wasm-and-webcontainers/). I've no clue what level of processing power it requires, whether it's feasible on a mobile device, etc.

**Comment by swissspidy** [comment]
libvips is already setup in this project, so I‘d probably start with that. Though it would be nice being able to use with other encoders as well.

**Comment by kleisauke** [comment]
Here's an online wasm-vips demo that uses the [`attention`](https://www.libvips.org/API/current/libvips-conversion.html#VIPS-INTERESTING-ATTENTION:CAPS) strategy:
https://kleisauke.github.io/wasm-vips/playground/?modules=#smartcrop

Note that Wasm support in sharp v0.33.0 requires a Node.js compatible runtime, making it currently incompatible with web browsers.
